export const  INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS'
export const  FETCH_SMILES_REQUEST = 'FETCH_SMILES_REQUEST'
export const  FETCH_SMILES_SUCCESS = 'FETCH_SMILES_SUCCESS'
export const  FETCH_SMILES_FAILURE = 'FETCH_SMILES_FAILURE'
export const  FETCH_SMILE_TODAY_SUCCESS = 'FETCH_SMILE_TODAY_SUCCESS'

export const  FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const  FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const  FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'
export const  FETCH_TODAY_NUMBER = 'FETCH_TODAY_NUMBER'


export const  FETCH_NOTES_REQUEST = 'FETCH_NOTES_REQUEST'
export const  FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE'
export const  FETCH_NOTES_DAY = 'FETCH_NOTES_DAY'
export const  ADD_NOTE = 'ADD_NOTE'